name: 'Terraform CI/CD Pipeline'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      env:
        ARM_CLIENT_ID: "de021fdd-06ac-413f-b247-0868fad8089c"
        ARM_CLIENT_SECRET: "1GC8Q~AzmZAMKZxCKX2cZ7IH50SEldEEidFlXawz"
        ARM_SUBSCRIPTION_ID: "61e822a8-75be-427e-9026-e3b5d46fdd22"
        ARM_TENANT_ID: "a8a6d952-dc1e-4b83-97e1-18ff70df777f"

    - name: Terraform Plan
      run: terraform plan -input=false
      env:
        ARM_CLIENT_ID: "de021fdd-06ac-413f-b247-0868fad8089c"
        ARM_CLIENT_SECRET: "1GC8Q~AzmZAMKZxCKX2cZ7IH50SEldEEidFlXawz"
        ARM_SUBSCRIPTION_ID: "61e822a8-75be-427e-9026-e3b5d46fdd22"
        ARM_TENANT_ID: "a8a6d952-dc1e-4b83-97e1-18ff70df777f"

  terraform-apply:
    name: 'Terraform Apply'
    needs: terraform-plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      env:
        ARM_CLIENT_ID: "de021fdd-06ac-413f-b247-0868fad8089c"
        ARM_CLIENT_SECRET: "1GC8Q~AzmZAMKZxCKX2cZ7IH50SEldEEidFlXawz"
        ARM_SUBSCRIPTION_ID: "61e822a8-75be-427e-9026-e3b5d46fdd22"
        ARM_TENANT_ID: "a8a6d952-dc1e-4b83-97e1-18ff70df777f"

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
      env:
        ARM_CLIENT_ID: "de021fdd-06ac-413f-b247-0868fad8089c"
        ARM_CLIENT_SECRET: "1GC8Q~AzmZAMKZxCKX2cZ7IH50SEldEEidFlXawz"
        ARM_SUBSCRIPTION_ID: "61e822a8-75be-427e-9026-e3b5d46fdd22"
        ARM_TENANT_ID: "a8a6d952-dc1e-4b83-97e1-18ff70df777f"
